### ISSUE TITLE
Rename output file

### ISSUE THREAD

**Issue by mathiasrw** [houshuang/madoko#1]
A questions for CLI interface (installed with npm) 

Is it possible to rename the generated file?

Its handy to name the markdown file something like "content" or "chapter1" but in the generated folder it must be `index`(.html). 

At the moment I just `mv filename.html index.html` but it feels a bit clumsy

**Comment by houshuang** [comment]
Note that I just imported this to make it available on Github, for feedback you should go here: https://madoko.codeplex.com/
